server:
  port: 0 # 0번 port를 사용하겠다는 의가 아님. 사용되지 않는 port번호를 임의로 할당해달라는 의미...
  
spring:
  application:
    name: sell-service
    
#  h2: # h2 데이터베이스 설정
#    console:
#      enabled: true # 브라우저에에서 콘솔을 볼 수 있게 하겠다.
#      settings:
#        web-allow-others: true
#      path: /h2-console # url
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://axiology.iptime.org:3306/negodb?serverTimezone=Asia/Seoul
    username: axiology
    password: "#dpsldkr#"
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true 
      
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${HOSTNAME}
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://discovery-service-0.discovery-service.default.svc.cluster.local:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, beans, env
      
      
ver: dev.2023.08.28.03
