server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
       git:
         uri: https://github.com/axiology83/usedshop-config.git
         username: username
         password: password
         # uri: file:C:\\work\\git-repo
  application:
    name: config-service

    
ver: dev.2023.08.27.001
