name: Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      id: build
      run: |
        TAG="dev.$(date +'%Y.%m.%d')"
        CHANGED_SERVICES=""
        for dir in */ ; do
          if [ -f "$dir/pom.xml" ]; then
            APP_NAME=$(basename $dir)
            if git diff --name-only HEAD~1 HEAD | grep -q "$dir"; then
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:$TAG $dir
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:$TAG
              CHANGED_SERVICES="$CHANGED_SERVICES $APP_NAME"
            fi
          fi
        done
        echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV

    - name: Save changed services list
      if: env.CHANGED_SERVICES != ''
      run: echo "$CHANGED_SERVICES" > changed_services.txt

    - name: Upload changed services list
      if: env.CHANGED_SERVICES != ''
      uses: actions/upload-artifact@v2
      with:
        name: changed_services
        path: changed_services.txt
