name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download changed services list
      uses: actions/download-artifact@v2
      with:
        name: changed_services

    - name: Deploy to Kubernetes
      run: |
        TAG="dev.$(date +'%Y.%m.%d')"
        CHANGED_SERVICES=$(cat changed_services.txt)
        for service in $CHANGED_SERVICES; do
          sed -i "s/IMAGE_TAG_PLACEHOLDER/$TAG/g" $service/deployment.yml
          kubectl apply -f $service/deployment.yml
        done
