name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Download changed services list
      uses: actions/download-artifact@v2
      with:
        name: changed_services

    - name: Deploy to Kubernetes
      run: |
        TAG="dev.$(date +'%Y.%m.%d')"
        CHANGED_SERVICES=$(cat changed_services.txt)
        
        for service in $CHANGED_SERVICES; do
          # Modify the deployment file as needed
          sed -i "s/IMAGE_TAG_PLACEHOLDER/$TAG/g" /home/axiology/usershop/$service.yml

          # Deploy to Kubernetes
          kubectl apply -f /home/axiology/usershop/$service.yml
        done
