name: force-start

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, tiny-eniac]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Kubernetes
      run: |
        TAG="ver0.0.0"
        for file in /home/axiology/usedshop/*.yml; do
          temp_file=$(mktemp)
          cp $file $temp_file
          sed -i "s/IMAGE_TAG_PLACEHOLDER/$TAG/g" $temp_file
          kubectl apply -f $temp_file
          rm $temp_file
        done

