name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes
      run: |
        TAG="dev.$(date +'%Y.%m.%d')"
        for file in /home/axiology/usedshop/*.yml; do
          temp_file=$(mktemp)
          cp $file $temp_file
          sed -i "s/IMAGE_TAG_PLACEHOLDER/$TAG/g" $temp_file
          kubectl apply -f $temp_file
          rm $temp_file
        done

